### ISSUE TITLE
panic on unlock of unlocked mutex

### ISSUE THREAD

**Issue by bundgaard** [proullon/ramsql#81]
Hi @proullon 

Receiving panic from using sql.Db#Begin, sql.Db.Commit(), sql.Db.Rollback

```
2023/08/02 23:01:39 incoming messages 32345, elapsed seconds since start   41, routes 0
fatal error: sync: unlock of unlocked mutex

goroutine 596 [running]:
sync.fatal({0x7ff616d2d069?, 0x20?})
        C:/Users/Users/sdk/go1.20.3/src/runtime/panic.go:1031 +0x1e
sync.(*Mutex).unlockSlow(0xc00010e000, 0xffffffff)
        C:/Users/Users/sdk/go1.20.3/src/sync/mutex.go:229 +0x3c
sync.(*Mutex).Unlock(0x1?)
        C:/Users/Users/sdk/go1.20.3/src/sync/mutex.go:223 +0x29
github.com/proullon/ramsql/driver.(*Stmt).Exec(0xc0008fa240, {0xc00078b7a0?, 0xc0008fa240?, 0x0?})
        C:/Users/Users/go/pkg/mod/github.com/proullon/ramsql@v0.0.1/driver/stmt.go:108 +0x32e
database/sql.ctxDriverStmtExec({0x7ff616dbade8, 0xc00001c040}, {0x7ff616dbafa8, 0xc0008fa240}, {0xc000928480?, 0x3, 0x3})
        C:/Users/Users/sdk/go1.20.3/src/database/sql/ctxutil.go:77 +0x1f9
database/sql.resultFromStatement({0x7ff616dbade8, 0xc00001c040}, {0x7ff616dba840, 0xc00010e000}, 0xc0000a2440, {0xc0013bd738, 0x3, 0x3})
        C:/Users/Users/sdk/go1.20.3/src/database/sql/sql.go:2635 +0x145
database/sql.(*Stmt).ExecContext.func1(0x8?)
        C:/Users/Users/sdk/go1.20.3/src/database/sql/sql.go:2609 +0xa7
database/sql.(*DB).retry(0x20?, 0xc0013bd548)
        C:/Users/Users/sdk/go1.20.3/src/database/sql/sql.go:1538 +0x47
database/sql.(*Stmt).ExecContext(0xc001552064?, {0x7ff616dbade8?, 0xc00001c040?}, {0xc0013bd738?, 0x0?, 0x0?})
        C:/Users/Users/sdk/go1.20.3/src/database/sql/sql.go:2603 +0x17c
database/sql.(*Stmt).Exec(...)
        C:/Users/Users/sdk/go1.20.3/src/database/sql/sql.go:2623
main.insertRoute(0xc000554050?, 0xc0006064b0)
        C:/Code/backend_backend/simple/repository.go:67 +0x665
main.(*ramsqlRepository).Insert(0xc00010e2e0, 0xc0000bf0e0?)
        C:/Code/backend_backend/simple/ramsql.go:36 +0x7e
main.shipReachedDestination.func1({0x7ff616d0fda0?, 0x35520e6829?}, 0xc0008e4200)
        C:/Code/backend_backend/simple/main.go:316 +0x388
net/http.HandlerFunc.ServeHTTP(0xc00007c800?, {0x7ff616dbaba0?, 0xc000918540?}, 0xc0013bd938?)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0013bd950?, {0x7ff616dbaba0, 0xc000918540}, 0xc0008e4200)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2500 +0x149
net/http.StripPrefix.func1({0x7ff616dbaba0, 0xc000918540}, 0xc0008e4100)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2165 +0x332
net/http.HandlerFunc.ServeHTTP(0x7ff6167f7460?, {0x7ff616dbaba0?, 0xc000918540?}, 0x7ff6167f6ddd?)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x3b?, {0x7ff616dbaba0, 0xc000918540}, 0xc0008e4100)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2500 +0x149
main.countIncomingRequests.func1({0x7ff616dbaba0, 0xc000918540}, 0xc0013bdad0?)
        C:/Code/backend_backend/simple/main.go:116 +0x68
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7ff616dbaba0?, 0xc000918540?}, 0x7ff616abef34?)
        C:/Users/Users/sdk/go1.20.3/src/net/http/server.go:2122 +0x2f

```

**Comment by proullon** [comment]
Hi,

I recently merged in master a complete rewrite. Can you go get ramsql@master and check if you run into the same issue ?

**Comment by proullon** [comment]
Alright, I'll check tests coverage, thanks

**Comment by proullon** [comment]
Hi,

There was indeed an issue with transactions on `master`, now fixed.
