### ISSUE TITLE
Panic when trying to limit query results from an empty table

### ISSUE THREAD

**Issue by pbacsko** [proullon/ramsql#95]
I've been investigating ramsql with GORM.

I believe I ran into a bug. The following code is invoked from Go:

```
	if err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		return s.db.Last(&result, "test_id= ?", id).Error
	}); err != nil {
		return 0, nil, err
	}
```

The generated SQL query by GORM:
```
SELECT * FROM "event_db_entries" WHERE test_id= $1 ORDER BY "event_db_entries"."test_id" DESC LIMIT 1
```

Panic with call stack:
```
panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 73 [running]:
github.com/proullon/ramsql/engine/agnostic.(*LimitSorter).Exec(0xc00034e180)
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/engine/agnostic/predicate.go:431 +0x65
github.com/proullon/ramsql/engine/agnostic.(*SelectorNode).Exec(0xc000332500)
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/engine/agnostic/predicate.go:1170 +0x36
github.com/proullon/ramsql/engine/agnostic.(*Transaction).Query(0xc00032a6c0, {0x0?, 0x0?}, {0xc00033c390?, 0xc000334084?, 0x18?}, {0xfa0968?, 0xc00035a240?}, {0x0, 0x0, ...}, ...)
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/engine/agnostic/transaction.go:504 +0x1bb
github.com/proullon/ramsql/engine/executor.selectExecutor(0xc00034e0a8, 0xc00032b2f0, {0xc00032a780, 0x1, 0x1})
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/engine/executor/engine.go:545 +0xd8c
github.com/proullon/ramsql/engine/executor.(*Tx).QueryContext(0xc00034e0a8, {0x15?, 0xc000371088?}, {0xc000372000?, 0x1?}, {0xc00032a780, 0x1, 0x1})
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/engine/executor/tx.go:82 +0xe6
github.com/proullon/ramsql/driver.(*Conn).QueryContext(0xc00033c200, {0xf9e068, 0x1604da0}, {0xc000372000, 0x6e}, {0xc00032a690, 0x1, 0x15ff768?})
	/home/bacskop/go/pkg/mod/github.com/proullon/ramsql@v0.1.3/driver/conn.go:175 +0x29b
database/sql.ctxDriverQuery({0xf9e068?, 0x1604da0?}, {0x7fa08cae28d8?, 0xc00033c200?}, {0x0?, 0x0?}, {0xc000372000?, 0xdbe900?}, {0xc00032a690, 0x1, ...})
	/snap/go/current/src/database/sql/ctxutil.go:48 +0xd7
database/sql.(*DB).queryDC.func1()
	/snap/go/current/src/database/sql/sql.go:1748 +0x165
database/sql.withLock({0xf98510, 0xc0003302d0}, 0xc000371370)
	/snap/go/current/src/database/sql/sql.go:3502 +0x82
database/sql.(*DB).queryDC(0xc0003d5401?, {0xf9e068, 0x1604da0}, {0x0, 0x0}, 0xc0003302d0, 0xc00033c210, {0xc000372000, 0x6e}, {0xc000362100, ...})
	/snap/go/current/src/database/sql/sql.go:1743 +0x209
database/sql.(*DB).query(0xc000100000?, {0xf9e068, 0x1604da0}, {0xc000372000, 0x6e}, {0xc000362100, 0x1, 0x8}, 0xc5?)
	/snap/go/current/src/database/sql/sql.go:1726 +0xfc
database/sql.(*DB).QueryContext.func1(0xcf?)
	/snap/go/current/src/database/sql/sql.go:1704 +0x4f
database/sql.(*DB).retry(0x10?, 0xc000371558)
	/snap/go/current/src/database/sql/sql.go:1538 +0x42
database/sql.(*DB).QueryContext(0xc00032a420?, {0xf9e068?, 0x1604da0?}, {0xc000372000?, 0x0?}, {0xc000362100?, 0x4105a5?, 0x0?})
	/snap/go/current/src/database/sql/sql.go:1703 +0xc5
gorm.io/gorm/callbacks.Query(0xc00032a420)
	/home/bacskop/go/pkg/mod/gorm.io/gorm@v1.25.4/callbacks/query.go:20 +0xb2
gorm.io/gorm.(*processor).Execute(0xc000273590, 0xc000401410?)
	/home/bacskop/go/pkg/mod/gorm.io/gorm@v1.25.4/callbacks.go:130 +0x375
gorm.io/gorm.(*DB).Last(0xc000334050?, {0xca9dc0?, 0xc000330120}, {0xc00035a060, 0x2, 0x2})
	/home/bacskop/go/pkg/mod/gorm.io/gorm@v1.25.4/finisher_api.go:158 +0x1f2
```

The "event_db_entries" table has no rows at this point. It looks like `LimitSorter.Exec()` needs to handle the case when `len(res) == 0`.

**Comment by proullon** [comment]
Hi,
Thanks for reporting !
